name: mk3_env
channels:
  - conda-forge
  - cantera
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pyyaml
  - jupyter
  - cantera=3.2.0
  - dill
  - mpi4py
  - pip
  - zeus-mcmc
